a = int(input("Enter a number = "))
b = float(input("Enter a number = "))
c = str(input("Enter a string = "))
d = list(map(int,input("Enter elements separated by spaces = ").split()))
e = tuple(map(int,input("Enter elements separated by spaces = ").split()))
print("The datatype of a is = ", type(a))
print("The datatype of b is = ", type(b))
